Filter out duplicate descriptors from diamond inheritance
This unfortunately isn't a complete fix because without updating the SerializerModule to have an explicit mapping that shouldn't be needed, you end up getting this stacktrace:

Class 'NegateExpr' is not registered for polymorphic serialization in the scope of 'Expr'.
kotlinx.serialization.SerializationException: Class 'NegateExpr' is not registered for polymorphic serialization in the scope of 'Expr'.
Mark the base class as 'sealed' or register the serializer explicitly.
	at kotlinx.serialization.internal.AbstractPolymorphicSerializerKt.throwSubtypeNotRegistered(AbstractPolymorphicSerializer.kt:102)
	at kotlinx.serialization.internal.AbstractPolymorphicSerializerKt.throwSubtypeNotRegistered(AbstractPolymorphicSerializer.kt:113)
	at kotlinx.serialization.PolymorphicSerializerKt.findPolymorphicSerializer(PolymorphicSerializer.kt:96)
	at kotlinx.serialization.internal.AbstractPolymorphicSerializer.serialize(AbstractPolymorphicSerializer.kt:32)
	at kotlinx.serialization.encoding.Encoder$DefaultImpls.encodeSerializableValue(Encoding.kt:282)
	at kotlinx.serialization.encoding.AbstractEncoder.encodeSerializableValue(AbstractEncoder.kt:18)
	at kotlinx.serialization.encoding.AbstractEncoder.encodeSerializableElement(AbstractEncoder.kt:80)
	at com.github.avrokotlin.avro4k.schema.ReferencingMixedPolymorphic.write$Self(MixedPolymorphicSchemaTest.kt:40)
	at com.github.avrokotlin.avro4k.schema.ReferencingMixedPolymorphic$$serializer.serialize(MixedPolymorphicSchemaTest.kt:40)
	at com.github.avrokotlin.avro4k.schema.ReferencingMixedPolymorphic$$serializer.serialize(MixedPolymorphicSchemaTest.kt:40)
	at kotlinx.serialization.encoding.Encoder$DefaultImpls.encodeSerializableValue(Encoding.kt:282)
	at kotlinx.serialization.encoding.AbstractEncoder.encodeSerializableValue(AbstractEncoder.kt:18)
	at com.github.avrokotlin.avro4k.Avro.toRecord(Avro.kt:240)
	at com.github.avrokotlin.avro4k.Avro$openOutputStream$builder$1$1.invoke(Avro.kt:217)
	at com.github.avrokotlin.avro4k.Avro$openOutputStream$builder$1$1.invoke(Avro.kt:217)

I'm not sure what the proper solution to this is